import { createHash } from "node:crypto";
import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const remotionRoot = path.resolve(process.cwd());
const websiteRoot = path.resolve(remotionRoot, "..");
const repoRoot = path.resolve(websiteRoot, "..");
const output = path.join(remotionRoot, "public/assets");
await mkdir(output, { recursive: true });

const sources = [
  { name: "godfin-vault-dial.png", path: path.join(websiteRoot, "public/godfin-vault-dial.png"), provenance: "generated by scripts/generate_brand_assets.py from the canonical Vault Dial source" },
  { name: "demo-data.json", path: path.join(websiteRoot, "public/demo/demo-data.json"), provenance: "verified public snapshot of backend/tests/fixtures/golden_ledger_v1.json" },
  { name: "geist-latin.woff2", path: path.join(websiteRoot, "node_modules/next/dist/next-devtools/server/font/geist-latin.woff2"), provenance: "font distributed in the pinned Next.js dependency" },
];

const manifest = {
  schema_version: 1,
  source_repo_sha: "a668ab800f9a98b25ca9af13188d2ae14049ab23",
  source_date_epoch: 1788048000,
  public_output: true,
  external_network_required_at_render: false,
  audio: "none",
  sources: [],
};

for (const source of sources) {
  const bytes = await readFile(source.path);
  const scan = source.name.endsWith(".json") ? bytes.toString("utf8") : "";
  for (const forbidden of [
    /GODFIN-(?:PRO|MAX|BETA)-[A-Z0-9-]{12,}/i,
    /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i,
    /\b[A-Z]{4}0[A-Z0-9]{6}\b/,
    /\b[a-z0-9._-]{2,}@[a-z]{2,}\b/i,
  ]) {
    if (forbidden.test(scan)) throw new Error(`Private-looking content rejected from ${source.name}`);
  }
  await cp(source.path, path.join(output, source.name));
  manifest.sources.push({
    file: source.name,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    bytes: bytes.length,
    provenance: source.provenance,
  });
}

await writeFile(path.join(output, "provenance.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
console.log(`Prepared ${manifest.sources.length} allowlisted public Remotion assets.`);
