import { createHash } from "node:crypto";
import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const remotionRoot = path.resolve(process.cwd());
const websiteRoot = path.resolve(remotionRoot, "..");
const output = path.join(remotionRoot, "public/assets");
const captureOutput = path.join(output, "captures");
const audioOutput = path.join(output, "audio");
await mkdir(output, { recursive: true });
await mkdir(captureOutput, { recursive: true });
await mkdir(audioOutput, { recursive: true });

const captureProvenance = JSON.parse(
  await readFile(
    path.join(websiteRoot, "public/screenshots/real-app/provenance.json"),
    "utf8",
  ),
);

const sources = [
  { name: "godfin-vault-dial.png", path: path.join(websiteRoot, "public/godfin-vault-dial.png"), provenance: "generated by scripts/generate_brand_assets.py from the canonical Vault Dial source" },
  { name: "geist-latin.woff2", path: path.join(websiteRoot, "node_modules/next/dist/next-devtools/server/font/geist-latin.woff2"), provenance: "font distributed in the pinned Next.js dependency" },
  {
    name: "audio/godfin-beta-hero-narration.wav",
    path: path.join(remotionRoot, "source-assets/godfin-beta-hero-narration.wav"),
    provenance: "generated on the private DGX Spark with the Apache-2.0 Qwen3-TTS 0.6B CustomVoice model and built-in Aiden voice; no voice cloning or personal reference audio",
  },
];

for (const name of [
  "dashboard.png",
  "upload.png",
  "transactions.png",
  "review.png",
  "budget.png",
  "subscriptions.png",
  "reports.png",
  "cash-flow.png",
  "net-worth.png",
  "behavior-insights.png",
]) {
  sources.push({
    name: `captures/${name}`,
    path: path.join(websiteRoot, "public/screenshots/real-app", name),
    provenance: "captured from the actual GODFIN desktop frontend using the canonical in-memory synthetic household",
  });
}

const manifest = {
  schema_version: 2,
  source_repo_sha:
    process.env.GODFIN_SOURCE_SHA || captureProvenance.source_git_sha,
  canonical_golden_fixture:
    captureProvenance.canonical_golden_fixture,
  canonical_golden_fixture_sha256:
    captureProvenance.canonical_golden_fixture_sha256,
  capture_provenance_sha256: createHash("sha256")
    .update(JSON.stringify(captureProvenance))
    .digest("hex"),
  source_date_epoch: 1788048000,
  public_output: true,
  external_network_required_at_render: false,
  audio: {
    file: "audio/godfin-beta-hero-narration.wav",
    model: "Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice",
    model_revision: "85e237c12c027371202489a0ec509ded67b5e4b5",
    model_license: "Apache-2.0",
    model_license_url: "https://huggingface.co/Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice",
    speaker: "Aiden",
    voice_source: "model-provided synthetic preset",
  },
  sources: [],
};

for (const source of sources) {
  const bytes = await readFile(source.path);
  const scan = source.name.endsWith(".json") ? bytes.toString("utf8") : "";
  for (const forbidden of [
    /GODFIN-(?:PRO|MAX|BETA)-[A-Z0-9-]{12,}/i,
    /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i,
    /\b[A-Z]{4}0[A-Z0-9]{6}\b/,
    /\b[a-z0-9._-]{2,}@[a-z]{2,}\b/i,
  ]) {
    if (forbidden.test(scan)) throw new Error(`Private-looking content rejected from ${source.name}`);
  }
  await cp(source.path, path.join(output, source.name));
  manifest.sources.push({
    file: source.name,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    bytes: bytes.length,
    provenance: source.provenance,
  });
}

await writeFile(path.join(output, "provenance.json"), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
console.log(`Prepared ${manifest.sources.length} allowlisted public Remotion assets.`);
