"""initial_schema

Revision ID: fb6d6075f0bf
Revises: 
Create Date: 2026-02-27 22:54:14.192234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6d6075f0bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('last_4_digits', sa.String(length=4), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_saved', sa.Float(), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('pressure_level', sa.String(length=20), nullable=False),
    sa.Column('annual_return_rate', sa.Float(), nullable=False),
    sa.Column('minimum_flexible_floor', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('last_detected_date', sa.Date(), nullable=True),
    sa.Column('last_detected_amount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raw_string', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('embedding_vector', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=50), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('is_person', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('system_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_aggregates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('total_spend', sa.Float(), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=False),
    sa.Column('savings_rate', sa.Float(), nullable=True),
    sa.Column('fixed_total', sa.Float(), nullable=False),
    sa.Column('semi_flexible_total', sa.Float(), nullable=False),
    sa.Column('flexible_total', sa.Float(), nullable=False),
    sa.Column('transfer_total', sa.Float(), nullable=False),
    sa.Column('recurring_total', sa.Float(), nullable=False),
    sa.Column('category_breakdown', sa.Text(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('audit_session_id', sa.String(length=36), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['audit_session_id'], ['audit_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_normalized', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('avg_amount', sa.Float(), nullable=False),
    sa.Column('amount_stddev', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('avg_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_occurrence', sa.Date(), nullable=True),
    sa.Column('next_expected', sa.Date(), nullable=True),
    sa.Column('times_detected', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('merchant_raw', sa.String(length=255), nullable=True),
    sa.Column('merchant_normalized', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classification_source', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_type', sa.String(length=20), nullable=True),
    sa.Column('is_split', sa.Boolean(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('vpa_handle', sa.String(length=100), nullable=True),
    sa.Column('upi_ref_number', sa.String(length=50), nullable=True),
    sa.Column('email_message_id', sa.String(length=100), nullable=True),
    sa.Column('checksum_source', sa.String(length=64), nullable=True),
    sa.Column('checksum_canonical', sa.String(length=64), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('classification_version', sa.Integer(), nullable=False),
    sa.Column('audit_session_id', sa.String(length=36), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['audit_session_id'], ['audit_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_transactions_category', ['category'], unique=False)
        batch_op.create_index('ix_transactions_checksum_canonical', ['checksum_canonical'], unique=False)
        batch_op.create_index('ix_transactions_checksum_source', ['checksum_source'], unique=False)
        batch_op.create_index('ix_transactions_date', ['date'], unique=False)
        batch_op.create_index('ix_transactions_email_message_id', ['email_message_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('field_changed', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_splits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_transaction_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_splits')
    op.drop_table('audit_log')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_email_message_id')
        batch_op.drop_index('ix_transactions_date')
        batch_op.drop_index('ix_transactions_checksum_source')
        batch_op.drop_index('ix_transactions_checksum_canonical')
        batch_op.drop_index('ix_transactions_category')
        batch_op.drop_index('ix_transactions_account_id')

    op.drop_table('transactions')
    op.drop_table('recurring_patterns')
    op.drop_table('monthly_aggregates')
    op.drop_table('system_log')
    op.drop_table('merchant_memory')
    op.drop_table('income_sources')
    op.drop_table('goals')
    op.drop_table('classification_rules')
    op.drop_table('audit_sessions')
    op.drop_table('app_settings')
    op.drop_table('accounts')
    # ### end Alembic commands ###
