#!/usr/bin/env python3
"""Generate deterministic documentation facts from repository sources."""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "generated" / "STACK_FACTS.md"


def _json(path: str) -> dict:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def _settings_defaults() -> dict[str, object]:
    tree = ast.parse(
        (ROOT / "backend/app/core/config.py").read_text(encoding="utf-8")
    )
    settings_class = next(
        node
        for node in tree.body
        if isinstance(node, ast.ClassDef) and node.name == "Settings"
    )
    values: dict[str, object] = {}
    for node in settings_class.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        if node.value is not None:
            values[node.target.id] = ast.literal_eval(node.value)
    return values


def _match(path: str, pattern: str, label: str) -> str:
    text = (ROOT / path).read_text(encoding="utf-8")
    match = re.search(pattern, text)
    if not match:
        raise ValueError(f"Could not resolve {label} from {path}")
    return match.group(1)


def collect_facts() -> list[tuple[str, str, str]]:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    frontend = _json("frontend/package.json")
    website = _json("website/package.json")
    desktop = _json("desktop/package.json")
    settings = _settings_defaults()
    frontend_port = _match(
        "frontend/vite.config.js",
        r"\bport:\s*(\d+)",
        "frontend port",
    )
    website_port = _match(
        "website/package.json",
        r'"dev"\s*:\s*"[^"]*\s-p\s+(\d+)',
        "website port",
    )
    ci_python = _match(
        ".github/workflows/ci.yml",
        r'python-version:\s*["\']([^"\']+)["\']',
        "CI Python version",
    )
    python_requirement = project["project"]["requires-python"]
    return [
        ("Backend app version", f"`{settings['VERSION']}`", "`backend/app/core/config.py`"),
        (
            "Supported Python",
            f"`{python_requirement}` (CI/release: `{ci_python}`)",
            "`pyproject.toml`, `.github/workflows/ci.yml`",
        ),
        (
            "Backend default",
            f"`{settings['HOST']}:{settings['PORT']}`",
            "`backend/app/core/config.py`",
        ),
        ("Frontend development port", f"`{frontend_port}`", "`frontend/vite.config.js`"),
        ("Frontend React", f"`{frontend['dependencies']['react']}`", "`frontend/package.json`"),
        ("Vite", f"`{frontend['devDependencies']['vite']}`", "`frontend/package.json`"),
        ("Website version", f"`{website['version']}`", "`website/package.json`"),
        ("Website development port", f"`{website_port}`", "`website/package.json`"),
        ("Next.js", f"`{website['dependencies']['next']}`", "`website/package.json`"),
        ("Website React", f"`{website['dependencies']['react']}`", "`website/package.json`"),
        ("Desktop version", f"`{desktop['version']}`", "`desktop/package.json`"),
        ("Electron", f"`{desktop['devDependencies']['electron']}`", "`desktop/package.json`"),
        (
            "License",
            f"`{desktop['license']}`",
            "`desktop/package.json`, `LICENSE`",
        ),
    ]


def render() -> str:
    lines = [
        "<!-- Generated by scripts/generate_documentation_facts.py. Do not hand-edit. -->",
        "# GODFIN generated stack facts",
        "",
        "| Fact | Value | Source |",
        "| --- | --- | --- |",
    ]
    lines.extend(f"| {name} | {value} | {source} |" for name, value, source in collect_facts())
    lines.extend(
        [
            "",
            "Generated facts describe repository configuration, not release approval.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"Wrote {OUTPUT.relative_to(ROOT)}")
        return 0
    actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if actual != expected:
        print(
            "Generated documentation facts are stale. Run: "
            "backend/venv/bin/python scripts/generate_documentation_facts.py --write",
            file=sys.stderr,
        )
        return 1
    print("Generated documentation facts match repository sources.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
