#!/usr/bin/env python3
"""Fail closed when GODFIN dependency surfaces drift across their boundaries."""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
RUNTIME_INPUT = BACKEND / "requirements.txt"
TEST_INPUT = BACKEND / "requirements-test.txt"
BUILD_INPUT = BACKEND / "requirements-build.txt"
LOCKS = {
    "runtime": BACKEND / "requirements-lock.txt",
    "test": BACKEND / "requirements-test-lock.txt",
    "build": BACKEND / "requirements-build-lock.txt",
}

RETIRED_OR_UNUSED = {
    "anthropic",
    "google-generativeai",
    "openai",
    "python-levenshtein",
}
TEST_ONLY = {"httpcore2", "httpx2", "httpx2-jsfetch", "pytest"}
BUILD_ONLY = {
    "altgraph",
    "macholib",
    "pefile",
    "pyinstaller",
    "pyinstaller-hooks-contrib",
    "pywin32-ctypes",
    "setuptools",
}
FORBIDDEN_RUNTIME_IMPORTS = {
    "anthropic",
    "google.generativeai",
    "google.genai",
    "httpx2",
    "levenshtein",
    "openai",
    "pytest",
}


def _canonicalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _lock_packages(path: Path) -> dict[str, str]:
    packages: dict[str, str] = {}
    text = path.read_text(encoding="utf-8")
    for match in re.finditer(
        r"^([A-Za-z0-9_.-]+)==([^ ;\\\n]+)(?:[^\n]*)\\\n"
        r"(?P<body>(?:\s+--hash=sha256:[a-f0-9]{64}(?: \\\n|\n))+)",
        text,
        flags=re.MULTILINE,
    ):
        name = _canonicalize(match.group(1))
        if name in packages and packages[name] != match.group(2):
            raise RuntimeError(f"{path.name} pins {name} more than once")
        packages[name] = match.group(2)

    declared = {
        _canonicalize(match.group(1))
        for match in re.finditer(
            r"^([A-Za-z0-9_.-]+)==([^ ;\\\n]+)", text, flags=re.MULTILINE
        )
    }
    missing_hashes = sorted(declared - packages.keys())
    if missing_hashes:
        raise RuntimeError(
            f"{path.name} has un-hashed requirements: {', '.join(missing_hashes)}"
        )
    return packages


def _assert_generated_header(path: Path, source: Path) -> None:
    header = "\n".join(path.read_text(encoding="utf-8").splitlines()[:3])
    expected = (
        "uv pip compile --universal --python-version 3.12 --generate-hashes "
        f"backend/{source.name} --output-file backend/{path.name}"
    )
    if expected not in header:
        raise RuntimeError(
            f"{path.name} was not generated by the reviewed Python 3.12 command"
        )


def _assert_input_contracts() -> None:
    runtime_text = RUNTIME_INPUT.read_text(encoding="utf-8").lower()
    test_lines = TEST_INPUT.read_text(encoding="utf-8").splitlines()
    build_lines = BUILD_INPUT.read_text(encoding="utf-8").splitlines()
    for retired in RETIRED_OR_UNUSED:
        if retired in runtime_text:
            raise RuntimeError(f"retired runtime dependency returned: {retired}")
    if test_lines[0].strip() != "-r requirements-lock.txt":
        raise RuntimeError("test requirements must extend the exact runtime lock")
    if build_lines[0].strip() != "-r requirements-lock.txt":
        raise RuntimeError("build requirements must extend the exact runtime lock")


def _assert_runtime_imports() -> None:
    findings: list[str] = []
    for path in sorted((BACKEND / "app").rglob("*.py")):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except SyntaxError as exc:
            raise RuntimeError(f"cannot inspect {path}: {exc}") from exc
        for node in ast.walk(tree):
            names: list[str] = []
            if isinstance(node, ast.Import):
                names = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and node.module:
                names = [node.module]
            for imported in names:
                lowered = imported.lower()
                if any(
                    lowered == forbidden or lowered.startswith(f"{forbidden}.")
                    for forbidden in FORBIDDEN_RUNTIME_IMPORTS
                ):
                    findings.append(
                        f"{path.relative_to(ROOT)}:{node.lineno}: {imported}"
                    )
    if findings:
        raise RuntimeError(
            "test-only or retired imports entered runtime source:\n- "
            + "\n- ".join(findings)
        )


def main() -> int:
    try:
        _assert_input_contracts()
        _assert_runtime_imports()
        packages = {
            surface: _lock_packages(path) for surface, path in LOCKS.items()
        }
        for surface, source in (
            ("runtime", RUNTIME_INPUT),
            ("test", TEST_INPUT),
            ("build", BUILD_INPUT),
        ):
            _assert_generated_header(LOCKS[surface], source)

        runtime = packages["runtime"]
        test = packages["test"]
        build = packages["build"]
        for name in RETIRED_OR_UNUSED | TEST_ONLY:
            if name in runtime or name in build:
                raise RuntimeError(f"{name} entered a production dependency surface")
        missing_test = sorted({"pytest", "httpx2"} - test.keys())
        if missing_test:
            raise RuntimeError(f"test lock is missing: {', '.join(missing_test)}")
        if "pyinstaller" not in build:
            raise RuntimeError("build lock is missing PyInstaller")
        if BUILD_ONLY & runtime.keys():
            raise RuntimeError("build-only packages entered the runtime lock")

        for name, version in runtime.items():
            if test.get(name) != version or build.get(name) != version:
                raise RuntimeError(
                    f"{name}=={version} is not identical across inherited locks"
                )
    except RuntimeError as exc:
        print(f"Dependency boundary verification failed: {exc}", file=sys.stderr)
        return 1

    print(
        "Dependency boundaries verified: runtime is minimal, test/build tooling "
        "is isolated, all locks are Python 3.12 universal hash locks."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
