"""Reviewed public-brand seed used only for exact canonical-name retrieval.

The catalog deliberately contains no bank-specific descriptors, VPAs, account
identifiers, or inferred aliases.  Each alias is exactly the public canonical
brand name, so GODFIN can use it as a candidate without claiming that an
arbitrary transaction descriptor belongs to that entity.
"""

from __future__ import annotations


# canonical name, entity type, category, subcategory
REVIEWED_MERCHANT_CATALOG_V1: tuple[
    tuple[str, str, str | None, str | None], ...
] = (
    ("Swiggy", "merchant", "FOOD & DINING", "Food Delivery"),
    ("Zomato", "merchant", "FOOD & DINING", "Food Delivery"),
    ("Domino's", "merchant", "FOOD & DINING", "Food Delivery"),
    ("McDonald's", "merchant", "FOOD & DINING", "Restaurants"),
    ("Starbucks", "merchant", "FOOD & DINING", "Coffee/Snacks"),
    ("Blinkit", "merchant", "FOOD & DINING", "Groceries"),
    ("BigBasket", "merchant", "FOOD & DINING", "Groceries"),
    ("Zepto", "merchant", "FOOD & DINING", "Groceries"),
    ("Swiggy Instamart", "merchant", "FOOD & DINING", "Groceries"),
    ("DMart", "merchant", "FOOD & DINING", "Groceries"),
    ("KFC", "merchant", "FOOD & DINING", "Restaurants"),
    ("Burger King", "merchant", "FOOD & DINING", "Restaurants"),
    ("Pizza Hut", "merchant", "FOOD & DINING", "Restaurants"),
    ("Subway", "merchant", "FOOD & DINING", "Restaurants"),
    ("Barbeque Nation", "merchant", "FOOD & DINING", "Restaurants"),
    ("Haldiram's", "merchant", "FOOD & DINING", "Restaurants"),
    ("Cafe Coffee Day", "merchant", "FOOD & DINING", "Coffee/Snacks"),
    ("FreshMenu", "merchant", "FOOD & DINING", "Food Delivery"),
    ("EatSure", "merchant", "FOOD & DINING", "Food Delivery"),
    ("Nature's Basket", "merchant", "FOOD & DINING", "Groceries"),
    ("Uber", "merchant", "TRANSPORTATION", "Ride Hailing"),
    ("Ola", "merchant", "TRANSPORTATION", "Ride Hailing"),
    ("Rapido", "merchant", "TRANSPORTATION", "Ride Hailing"),
    ("Namma Yatri", "merchant", "TRANSPORTATION", "Ride Hailing"),
    ("redBus", "merchant", "TRANSPORTATION", "Public Transit"),
    ("IRCTC", "government", "TRANSPORTATION", "Public Transit"),
    ("IndiGo", "merchant", "TRANSPORTATION", "Public Transit"),
    ("Air India", "merchant", "TRANSPORTATION", "Public Transit"),
    ("Akasa Air", "merchant", "TRANSPORTATION", "Public Transit"),
    ("MakeMyTrip", "merchant", "TRANSPORTATION", "Public Transit"),
    ("Goibibo", "merchant", "TRANSPORTATION", "Public Transit"),
    ("Cleartrip", "merchant", "TRANSPORTATION", "Public Transit"),
    ("IndianOil", "government", "TRANSPORTATION", "Fuel"),
    ("Bharat Petroleum", "government", "TRANSPORTATION", "Fuel"),
    ("Hindustan Petroleum", "government", "TRANSPORTATION", "Fuel"),
    ("Amazon India", "merchant", "SHOPPING", "Online Shopping"),
    ("Flipkart", "merchant", "SHOPPING", "Online Shopping"),
    ("Myntra", "merchant", "SHOPPING", "Clothing"),
    ("AJIO", "merchant", "SHOPPING", "Clothing"),
    ("Nykaa", "merchant", "SHOPPING", "Online Shopping"),
    ("Croma", "merchant", "SHOPPING", "Electronics"),
    ("Reliance Digital", "merchant", "SHOPPING", "Electronics"),
    ("Tata CLiQ", "merchant", "SHOPPING", "Online Shopping"),
    ("Meesho", "merchant", "SHOPPING", "Online Shopping"),
    ("Decathlon India", "merchant", "SHOPPING", "General"),
    ("IKEA India", "merchant", "SHOPPING", "Home/Kitchen"),
    ("Shoppers Stop", "merchant", "SHOPPING", "Clothing"),
    ("Lifestyle Stores", "merchant", "SHOPPING", "Clothing"),
    ("FirstCry", "merchant", "SHOPPING", "Online Shopping"),
    ("JioMart", "merchant", "SHOPPING", "Online Shopping"),
    ("Netflix", "merchant", "ENTERTAINMENT", "Subscriptions"),
    ("Spotify", "merchant", "ENTERTAINMENT", "Subscriptions"),
    ("JioHotstar", "merchant", "ENTERTAINMENT", "Subscriptions"),
    ("Prime Video", "merchant", "ENTERTAINMENT", "Subscriptions"),
    ("YouTube Premium", "merchant", "ENTERTAINMENT", "Subscriptions"),
    ("BookMyShow", "merchant", "ENTERTAINMENT", "Movies/Events"),
    ("PVR INOX", "merchant", "ENTERTAINMENT", "Movies/Events"),
    ("SonyLIV", "merchant", "ENTERTAINMENT", "Subscriptions"),
    ("ZEE5", "merchant", "ENTERTAINMENT", "Subscriptions"),
    ("Apple TV+", "merchant", "ENTERTAINMENT", "Subscriptions"),
    ("Steam", "merchant", "ENTERTAINMENT", "Gaming"),
    ("PlayStation", "merchant", "ENTERTAINMENT", "Gaming"),
    ("Airtel", "merchant", "UTILITIES & BILLS", "Internet/Phone"),
    ("Reliance Jio", "merchant", "UTILITIES & BILLS", "Internet/Phone"),
    ("Vi", "merchant", "UTILITIES & BILLS", "Internet/Phone"),
    ("BSNL", "government", "UTILITIES & BILLS", "Internet/Phone"),
    ("ACT Fibernet", "merchant", "UTILITIES & BILLS", "Internet/Phone"),
    ("Tata Play", "merchant", "UTILITIES & BILLS", "Subscriptions"),
    ("BESCOM", "government", "UTILITIES & BILLS", "Electricity"),
    ("Adani Electricity", "merchant", "UTILITIES & BILLS", "Electricity"),
    ("Tata Power", "merchant", "UTILITIES & BILLS", "Electricity"),
    ("Mahanagar Gas", "merchant", "UTILITIES & BILLS", "Gas"),
    ("Indraprastha Gas", "merchant", "UTILITIES & BILLS", "Gas"),
    ("Google One", "merchant", "UTILITIES & BILLS", "Subscriptions"),
    ("Microsoft 365", "merchant", "UTILITIES & BILLS", "Subscriptions"),
    ("Apple Services", "merchant", "UTILITIES & BILLS", "Subscriptions"),
    ("Adobe", "merchant", "UTILITIES & BILLS", "Subscriptions"),
    ("LIC", "financial", "FINANCIAL OBLIGATIONS", "Insurance Premium"),
    ("HDFC Life", "financial", "FINANCIAL OBLIGATIONS", "Insurance Premium"),
    ("SBI Life", "financial", "FINANCIAL OBLIGATIONS", "Insurance Premium"),
    ("ICICI Prudential", "financial", "FINANCIAL OBLIGATIONS", "Insurance Premium"),
    ("Zerodha", "financial", "FINANCIAL OBLIGATIONS", "SIP/Investment"),
    ("Groww", "financial", "FINANCIAL OBLIGATIONS", "SIP/Investment"),
    ("Upstox", "financial", "FINANCIAL OBLIGATIONS", "SIP/Investment"),
    ("Angel One", "financial", "FINANCIAL OBLIGATIONS", "SIP/Investment"),
    ("PhonePe", "financial", None, None),
    ("Paytm", "financial", None, None),
    ("Amazon Pay", "financial", None, None),
    ("CRED", "financial", None, None),
    ("Policybazaar", "financial", "FINANCIAL OBLIGATIONS", "Insurance Premium"),
    ("Apollo Pharmacy", "merchant", "HEALTH & WELLNESS", "Medical/Pharmacy"),
    ("Apollo Hospitals", "merchant", "HEALTH & WELLNESS", "Hospital"),
    ("MedPlus", "merchant", "HEALTH & WELLNESS", "Medical/Pharmacy"),
    ("Tata 1mg", "merchant", "HEALTH & WELLNESS", "Medical/Pharmacy"),
    ("PharmEasy", "merchant", "HEALTH & WELLNESS", "Medical/Pharmacy"),
    ("Practo", "merchant", "HEALTH & WELLNESS", "Medical/Pharmacy"),
    ("Cult.fit", "merchant", "HEALTH & WELLNESS", "Gym/Fitness"),
    ("Fortis Healthcare", "merchant", "HEALTH & WELLNESS", "Hospital"),
    ("Max Healthcare", "merchant", "HEALTH & WELLNESS", "Hospital"),
    ("Manipal Hospitals", "merchant", "HEALTH & WELLNESS", "Hospital"),
)


assert len(REVIEWED_MERCHANT_CATALOG_V1) == 100
